# Analytics
analytics:
  provider               : "google-gtag" # 구글 어날리틱스 등록 false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-156016699-1"
    anonymize_ip         : # true, false (default)
